name<-10L  #store integer values in name variable
typeof(name)
abc<-FALSE
typeof(abc)
Z<-3+4i
typeof(Z)
s<-"anchal"
typeof(s)
install.packages("dplyr")
cat<-c(11,33,44,66,23,78)
cat
typeof(cat)
is.double(cat)
str(cat)
cat=as.integer(cat)
cat1=as.character((cat))
typeof(cat)
class(cat1)
ls()
rm(cat1)
ls()
sqrt(12)
vect1<-c(12,45,67,78)
vector1=as.integer((vect1))
vect2<-c(17,40,7,70)
vector2=as.integer((vect2))
vector1
vector2
vector1+vector2
vector1-vector2
vector1*vector2
vector1/vector2
student_id<-c(1,2,3,4,5)
student_name<-c("a","b","c","d","e")
student<-data.frame(student_id,student_name)
student
typeof(student)
class(student)
student$student_id
nrow(student)
ncol(student)

mat<-matrix(c(1,2,3,4,5,6,7,8,9),nrow=3,ncol=3,byrow = TRUE)
mat
t<-cbind(mat)
t
t<-rbind(mat)
t
attributes(t)
cbind(c(1,2,3,4,5))
rbind(c(3,5,6,7,8))
list(1,2.33,"a",3+2i,TRUE)
setwd("C:/Users/user/Documents/Anchal's Files/R Studio")
getwd()
csvdata<-read.csv("myfile.csv")
csvdata
read.table("myfile.csv")
